Add startCli function
HTTP5214-Winter2023/TimeKeeper pull request #33
Opened 2023-03-01 13:41 UTC by Daniel320So

2023-03-01 21:13 UTC, wenhao-lu approved these changes

2023-03-01 21:13 UTC, wenhao-lu commented on app/src/command_line_interface/index.js
> +
Tested steps:
cd /app
npm i
npm start
prompt:  'Please provide your api key'
API key stored

2023-03-01 21:15 UTC, wenhao-lu approved these changes

2023-03-01 21:19 UTC, wenhao-lu requested changes
Great work!

2023-03-04 15:34 UTC, ceciaups approved these changes

2023-03-04 15:52 UTC, merged